# Setup
title:            From Scratch
tagline:          'Developer's Blog'
description:      'Just for Study'
url:              ''
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Janet'
  url:            ''

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
